version: '3.3'

  # Place your secret file somewhere on your host filesystem, with your password inside
secrets:
  mysql_password:
    file: ./secrets/mysql_password
  mysql_root_password:
    file: ./secrets/mysql_root_password

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - {{INSTANCE_ID}}_firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - 80:8080
    depends_on:
      - db

  db:
    image: mariadb
    restart: always
    environment:
      - MYSQL_USER=firefly
      - MYSQL_DATABASE=firefly
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
    volumes:
      - {{INSTANCE_ID}}_firefly_iii_db:/var/lib/mysql

  backup:
    image: fradelg/mysql-cron-backup:dependabot-docker-master-alpine-3.16.0
    depends_on:
      - db
    volumes:
      - ./mysql_backup:/backup
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=firefly
      - MYSQL_PASS_FILE=/run/secrets/mysql_root_password
      - MAX_BACKUPS=15
      - INIT_BACKUP=1
      - CRON_TIME=0 * * * * # Every hour at minute 0
      - GZIP_LEVEL=9 # High compression level


volumes:
   {{INSTANCE_ID}}_firefly_iii_upload:
   {{INSTANCE_ID}}_firefly_iii_db:
