version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    depends_on:
      - db
    ports:
      - 80:8080
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file:
      - environment/app.env

  db:
    hostname: fireflyiiidb
    image: mariadb
    restart: always
    volumes:
      - firefly_iii_db:/var/lib/mysql
    env_file:
      - environment/db.env

  #
  # fradelg/mysql-cron-backup
  #
  # scheduled backups of mysqldb dumps
  #
  backup-db:
    image: fradelg/mysql-cron-backup:dependabot-docker-master-alpine-3.16.0
    depends_on:
      - db
    volumes:
      - ./backups:/backup
    env_file:
      - environment/db-backup.env


  #
  # offen/docker-volume-backup
  #
  # scheduled backups of docker volume contents
  #
  # https://hub.docker.com/r/offen/docker-volume-backup
  # https://github.com/offen/docker-volume-backup/tree/main
  backup-files:
    image: offen/docker-volume-backup:v2
    depends_on:
      - app
    volumes:
      - firefly_iii_upload:/source/uploads
      - ./environment:/source/environment
      - ./docker-compose.yml:/source/docker-compose.yml
      - ./backups:/backup
    env_file:
      - environment/volume-backup.env

volumes:
   firefly_iii_upload:
   firefly_iii_db:
